Question 1:
Use Digit dataset and perform the Logistic Regression. Import the dataset from Sklearn

In [5]:
from sklearn.datasets import load_digits

In [8]:
digits = load_digits()

In [9]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
  'pixel_5_2',
  'pixel_5_3',
  'pixel_5_4',
  'pixel_5_5',
  'pixel_5_6',
  'pixel_5_7',
  'pixel_6_0',
  'pixel_6_1',
  'pixel_6_2',
  'pixel_6_3',
  'pixel_6_4',
  'pixel_6_5',
  'pixel_6_6',
  'pixel_6_7',
  'pixel_7_0',
  'pixel_7_1',
  'pixel_7_2',
  'pixel_7_3',
  'pixel_7_4',
  'pixel_7_5',
  'pixel_7_6',
  'pixel_7_7'],
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

        [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
         [ 0.,  0.,  3., ..., 14.,  0.,  0.],
         [ 0.,  0.,  8., ..., 16.,  0.,  0.],
         ...,
         [ 0.,  9., 16., ...,  0.,  0.,  0.],
         [ 0.,  3., 13., ..., 11.,  5.,  0.],
         [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

        ...,

        [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ...,  2.,  1.,  0.],
         [ 0.,  0., 16., ..., 16.,  5.,  0.],
         ...,
         [ 0.,  0., 16., ..., 15.,  0.,  0.],
         [ 0.,  0., 15., ..., 16.,  0.,  0.],
         [ 0.,  0.,  2., ...,  6.,  0.,  0.]],

        [[ 0.,  0.,  2., ...,  0.,  0.,  0.],
         [ 0.,  0., 14., ..., 15.,  1.,  0.],
         [ 0.,  4., 16., ..., 16.,  7.,  0.],
         ...,
         [ 0.,  0.,  0., ..., 16.,  2.,  0.],
         [ 0.,  0.,  4., ..., 16.,  2.,  0.],
         [ 0.,  0.,  5., ..., 12.,  0.,  0.]],

        [[ 0.,  0., 10., ...,  1.,  0.,  0.],
         [ 0.,  2., 16., ...,  1.,  0.,  0.],
         [ 0.,  0., 15., ..., 15.,  0.,  0.],
         ...,
         [ 0.,  4., 16., ..., 16.,  6.,  0.],
         [ 0.,  8., 16., ..., 16.,  8.,  0.],
         [ 0.,  1.,  8., ..., 12.,  1.,  0.]]]),
 'DESCR': ".. _digits_dataset:\n\nOptical recognition of handwritten digits dataset\n--------------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 5620\n    :Number of Attributes: 64\n    :Attribute Information: 8x8 image of integer pixels in the range 0..16.\n    :Missing Attribute Values: None\n    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n    :Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttps://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number of on pixels are counted in each block. This generates\nan input matrix of 8x8 where each element is an integer in the range\n0..16. This reduces dimensionality and gives invariance to small\ndistortions.\n\nFor info on NIST preprocessing routines, see M. D. Garris, J. L. Blue, G.\nT. Candela, D. L. Dimmick, J. Geist, P. J. Grother, S. A. Janet, and C.\nL. Wilson, NIST Form-Based Handprint Recognition System, NISTIR 5469,\n1994.\n\n.. topic:: References\n\n  - C. Kaynak (1995) Methods of Combining Multiple Classifiers and Their\n    Applications to Handwritten Digit Recognition, MSc Thesis, Institute of\n    Graduate Studies in Science and Engineering, Bogazici University.\n  - E. Alpaydin, C. Kaynak (1998) Cascading Classifiers, Kybernetika.\n  - Ken Tang and Ponnuthurai N. Suganthan and Xi Yao and A. Kai Qin.\n    Linear dimensionalityreduction using relevance weighted LDA. School of\n    Electrical and Electronic Engineering Nanyang Technological University.\n    2005.\n  - Claudio Gentile. A New Approximate Maximal Margin Classification\n    Algorithm. NIPS. 2000."}

In [10]:
digits.feature_names

['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

In [11]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [12]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [13]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
import pandas as pd
df = pd.DataFrame(digits.data)

In [16]:
df

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,4.0,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0
1796,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,8.0,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0

In [17]:
df.columns = digits.feature_names

In [18]:
df

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,4.0,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0
1796,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,8.0,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0

In [19]:
df.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_6,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0

In [20]:
from sklearn.linear_model import LogisticRegression   
from sklearn.model_selection import train_test_split

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

In [22]:
x_train , x_test , y_train , y_test = train_test_split(digits.data , digits.target , stratify =  digits.target , random_state = 30 , test_size = 0.3)

In [23]:
x_test

array([[ 0.,  0.,  9., ...,  1.,  0.,  0.],
       [ 0.,  1., 10., ...,  0.,  0.,  0.],
       [ 0.,  0., 11., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  8., ...,  9.,  0.,  0.],
       [ 0.,  1., 11., ..., 12.,  8.,  0.]])

In [24]:
y_test

array([2, 7, 3, 5, 6, 8, 5, 4, 3, 8, 9, 2, 7, 9, 5, 9, 3, 7, 8, 0, 8, 1,
       3, 4, 0, 2, 5, 3, 4, 3, 1, 0, 5, 4, 8, 6, 2, 1, 1, 7, 7, 1, 1, 2,
       8, 6, 8, 4, 1, 8, 1, 7, 9, 3, 5, 3, 8, 5, 5, 0, 2, 6, 0, 4, 2, 1,
       7, 8, 5, 9, 5, 5, 8, 5, 5, 8, 8, 4, 8, 4, 1, 4, 1, 5, 6, 2, 7, 7,
       9, 0, 3, 8, 5, 4, 9, 7, 3, 3, 7, 8, 4, 6, 7, 5, 0, 0, 0, 9, 9, 6,
       0, 3, 6, 1, 0, 3, 2, 1, 6, 6, 5, 4, 5, 9, 0, 5, 1, 0, 0, 5, 1, 7,
       9, 7, 6, 9, 5, 7, 1, 0, 4, 9, 4, 8, 8, 0, 9, 6, 3, 8, 3, 1, 4, 7,
       8, 4, 5, 7, 6, 1, 2, 2, 3, 5, 1, 5, 8, 5, 3, 5, 4, 4, 7, 6, 3, 8,
       2, 0, 1, 5, 2, 6, 5, 4, 3, 9, 7, 2, 4, 3, 3, 3, 0, 7, 9, 3, 7, 7,
       2, 1, 9, 1, 8, 3, 0, 7, 1, 2, 2, 4, 2, 9, 1, 0, 5, 6, 8, 6, 3, 0,
       5, 7, 3, 2, 6, 2, 2, 2, 0, 8, 0, 9, 0, 5, 1, 6, 0, 1, 0, 8, 9, 7,
       4, 4, 2, 0, 6, 2, 3, 4, 5, 7, 9, 2, 7, 7, 1, 6, 2, 4, 3, 9, 6, 6,
       1, 4, 3, 2, 6, 2, 4, 8, 3, 6, 5, 4, 9, 3, 0, 7, 1, 9, 5, 3, 7, 0,
       6, 1, 5, 9, 7, 4, 9, 9, 8, 5, 8, 5, 9, 6, 9, 6, 0, 5, 1, 1, 3, 8,
       7, 7, 7, 4, 7, 8, 6, 9, 1, 0, 9, 0, 5, 9, 6, 6, 5, 6, 1, 4, 1, 6,
       9, 4, 6, 7, 6, 7, 0, 5, 2, 2, 6, 9, 2, 2, 6, 8, 5, 9, 5, 0, 9, 0,
       3, 6, 1, 9, 8, 9, 1, 5, 1, 0, 8, 8, 9, 8, 3, 5, 3, 5, 5, 5, 1, 6,
       2, 4, 0, 7, 0, 9, 1, 1, 0, 6, 7, 3, 3, 3, 4, 7, 7, 8, 3, 2, 6, 9,
       0, 4, 0, 1, 4, 7, 8, 6, 1, 7, 2, 3, 9, 4, 0, 4, 2, 9, 7, 1, 8, 2,
       2, 0, 9, 0, 1, 2, 8, 8, 7, 8, 4, 6, 1, 4, 6, 4, 2, 2, 3, 6, 3, 3,
       6, 9, 7, 7, 0, 5, 0, 1, 4, 0, 9, 1, 1, 2, 9, 6, 5, 4, 5, 5, 9, 2,
       1, 4, 3, 2, 4, 7, 8, 0, 1, 8, 9, 8, 4, 4, 0, 8, 8, 1, 8, 8, 0, 9,
       7, 3, 4, 1, 5, 5, 8, 4, 8, 7, 9, 6, 3, 7, 9, 2, 3, 0, 1, 7, 2, 4,
       6, 9, 2, 2, 2, 3, 4, 3, 6, 2, 8, 1, 6, 4, 3, 5, 0, 0, 9, 3, 7, 2,
       6, 6, 6, 3, 0, 4, 2, 3, 7, 4, 3, 2])

In [25]:
y_train

array([9, 4, 6, ..., 9, 1, 8])

In [26]:
x_train

array([[ 0.,  0.,  9., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  8.,  0.,  0.],
       [ 0.,  0.,  0., ...,  6.,  0.,  0.],
       ...,
       [ 0.,  0.,  6., ..., 16.,  4.,  0.],
       [ 0.,  0.,  3., ..., 16., 16., 16.],
       [ 0.,  0., 15., ...,  7.,  0.,  0.]])

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
logR = LogisticRegression()

In [29]:
logR.fit(x_train , y_train)

C:\Users\pavan kumar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [30]:
y_pred = logR.predict(x_test)

In [31]:
y_pred

array([2, 7, 3, 5, 6, 8, 5, 4, 3, 8, 9, 2, 7, 9, 5, 9, 3, 7, 8, 0, 8, 1,
       3, 4, 0, 2, 5, 3, 4, 8, 1, 0, 5, 1, 8, 6, 2, 1, 1, 7, 7, 1, 1, 2,
       8, 6, 8, 4, 1, 8, 1, 7, 9, 3, 5, 3, 8, 5, 5, 0, 2, 6, 0, 4, 2, 1,
       9, 8, 5, 9, 5, 5, 8, 5, 5, 8, 8, 4, 8, 4, 1, 4, 1, 5, 6, 2, 7, 7,
       7, 0, 3, 8, 7, 4, 9, 7, 3, 3, 7, 8, 4, 6, 7, 5, 0, 0, 0, 9, 9, 6,
       0, 3, 6, 9, 0, 3, 2, 1, 6, 6, 5, 4, 5, 9, 0, 5, 1, 0, 0, 5, 1, 7,
       9, 7, 6, 9, 5, 7, 1, 0, 4, 9, 4, 8, 8, 0, 9, 6, 3, 8, 3, 1, 4, 7,
       8, 4, 5, 7, 6, 1, 2, 2, 3, 5, 1, 5, 8, 5, 3, 5, 4, 4, 7, 6, 3, 8,
       2, 0, 1, 5, 2, 6, 5, 4, 3, 9, 7, 2, 4, 3, 3, 3, 0, 7, 9, 3, 7, 7,
       2, 1, 9, 1, 8, 3, 0, 7, 1, 2, 2, 4, 2, 9, 1, 0, 5, 6, 8, 6, 3, 0,
       5, 7, 3, 2, 6, 2, 2, 2, 0, 8, 0, 9, 0, 5, 1, 6, 0, 1, 0, 8, 5, 7,
       4, 4, 2, 0, 6, 2, 3, 4, 5, 7, 9, 2, 7, 7, 1, 6, 2, 4, 3, 9, 6, 6,
       1, 4, 3, 2, 6, 2, 4, 8, 3, 6, 5, 4, 9, 3, 0, 7, 1, 9, 5, 3, 7, 0,
       6, 1, 5, 8, 9, 4, 9, 9, 8, 5, 8, 5, 9, 6, 9, 6, 0, 9, 1, 1, 2, 8,
       7, 7, 7, 4, 7, 8, 6, 9, 1, 0, 9, 0, 5, 9, 6, 6, 5, 6, 1, 4, 1, 6,
       9, 4, 6, 7, 6, 7, 0, 5, 2, 2, 6, 9, 2, 2, 6, 8, 5, 9, 5, 0, 9, 0,
       3, 6, 1, 9, 8, 9, 1, 5, 1, 0, 8, 8, 9, 9, 3, 5, 3, 5, 5, 5, 1, 6,
       2, 4, 0, 7, 0, 9, 1, 1, 0, 6, 7, 3, 3, 3, 4, 7, 7, 8, 3, 2, 6, 9,
       0, 4, 0, 1, 4, 7, 8, 6, 1, 7, 2, 3, 9, 4, 0, 4, 2, 9, 7, 1, 5, 2,
       2, 0, 9, 0, 1, 2, 8, 8, 7, 8, 4, 6, 1, 4, 6, 4, 2, 2, 5, 6, 3, 3,
       6, 9, 7, 7, 0, 5, 0, 1, 4, 0, 9, 1, 1, 2, 9, 6, 5, 4, 5, 5, 9, 2,
       1, 4, 3, 2, 4, 7, 8, 0, 1, 8, 9, 8, 4, 4, 0, 8, 8, 1, 8, 8, 0, 9,
       7, 3, 4, 1, 5, 5, 8, 4, 8, 7, 9, 6, 3, 7, 9, 2, 3, 0, 1, 7, 2, 4,
       6, 9, 2, 2, 2, 3, 4, 3, 6, 2, 8, 1, 6, 4, 3, 5, 0, 0, 9, 3, 7, 2,
       8, 6, 6, 3, 0, 4, 2, 3, 7, 4, 3, 2])

In [33]:
df_pred = pd.DataFrame()
df_pred['y_test'] = y_test
df_pred['y_pred'] = y_pred

In [34]:
df_pred

     y_test  y_pred
0         2       2
1         7       7
2         3       3
3         5       5
4         6       6
..      ...     ...
535       3       3
536       7       7
537       4       4
538       3       3
539       2       2

[540 rows x 2 columns]

In [36]:
import numpy as np
mislabel = np.sum((y_test!=y_pred))
print((mislabel))

15

In [37]:
len(y_test)

540

In [41]:
525/540

0.9722222222222222

In [42]:
from sklearn.metrics import accuracy_score
print("Accuracy of test set=",accuracy_score(y_test, y_pred)*100)

Accuracy of test set= 97.22222222222221

In [45]:
from sklearn.metrics import confusion_matrix

In [46]:
cm = confusion_matrix(y_test , y_pred)

In [47]:
cmdf = pd.DataFrame(cm,index=cancer.target_names,
                    columns=cancer.target_names)

In [48]:
cm

array([[54,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 54,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 0,  0, 53,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1, 52,  0,  1,  0,  0,  1,  0],
       [ 0,  1,  0,  0, 53,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 53,  0,  1,  0,  1],
       [ 0,  0,  0,  0,  0,  0, 53,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 52,  0,  2],
       [ 0,  0,  0,  0,  0,  1,  0,  0, 50,  1],
       [ 0,  0,  0,  0,  0,  1,  0,  1,  1, 51]], dtype=int64)

In [49]:
cmdf

    0   1   2   3   4   5   6   7   8   9
0  54   0   0   0   0   0   0   0   0   0
1   0  54   0   0   0   0   0   0   0   1
2   0   0  53   0   0   0   0   0   0   0
3   0   0   1  52   0   1   0   0   1   0
4   0   1   0   0  53   0   0   0   0   0
5   0   0   0   0   0  53   0   1   0   1
6   0   0   0   0   0   0  53   0   1   0
7   0   0   0   0   0   0   0  52   0   2
8   0   0   0   0   0   1   0   0  50   1
9   0   0   0   0   0   1   0   1   1  51